### ISSUE TITLE
Is it possible to cancel the clone trait. from par_find_colliding_pairs func params

### ISSUE THREAD

**Issue by droog126** [tiby312/broccoli#190]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/59406205/168022762-6226e79a-f3f5-4d45-b94f-286267ad5675.png">

Is the clone trait necessary?

**Comment by droog126** [comment]
4.0.1 versions

**Comment by droog126** [comment]
I want to find the collision pair in parallel, and use the closure to capture a hashmap to store the collision result, but I see that the parallel api needs clone trait, is there any way to solve this problem? I want to use parallel search.

**Comment by droog126** [comment]
let s = Rc::new(RefCell::new(HashMap::new()));
Seems like I can use rc refcell. I am trying.

**Comment by tiby312** [comment]
@droog126  I think I understand. I added `par_find_colliding_pairs_acc`. Let me know if that works. Each thread could build up a hashmap that then gets merged at the end. That way no need to lock anything on each collision.

**Comment by tiby312** [comment]
Forgot to link to example https://github.com/tiby312/broccoli/blob/master/examples/collision_par_acc.rs

**Comment by droog126** [comment]
love yoo

**Comment by droog126** [comment]
> @droog126 I think I understand. I added `par_find_colliding_pairs_acc`. Let me know if that works. Each thread could build up a hashmap that then gets merged at the end. That way no need to lock anything on each collision.

I tried this new api and the performance is not very good.Arc also is not good.I still try to put it directly in the inner.

**Comment by droog126** [comment]
All the pain comes from because, I might have two rectangles for one entity.

**Comment by droog126** [comment]
> @droog126 I snooped your code, if you insert bounding boxes that look like (Rect,&mut T) instead of (Rect,T), you should get better performance. Tree construction shuffles alot of stuff around and if T is big that can be big slowdown. I did some analysis on that here:
> 
> So I think you're hitting the case as descriped in the below report: And you can see the performance regress in graph: `Bench of rebal:256_bytes with abspiral(num,1.5)` https://tiby312.github.io/broccoli_report/ch4-aabb-data-layout.html
> 
> I looked at this part:
> 
> ```
> let mut newCollisionProductionFactor = collisionProductionFactor.clone();
> newCollisionProductionFactor.pos = globalTransform.translation.xy();
> dynBots.push(bbox(rect, newCollisionProductionFactor));
> ```
> 
> So your T is inserted directly and it is big size.
> 
> ```
> #[derive(Component, Clone)]
> pub struct CollisionProductionFactor {
>     pub id: Entity,
>     pub collisionType: CollisionType,
>     pub instanceType: InstanceType,
>     pub pos: Vec2,
> 
>     pub width: f32,
>     pub height: f32,
>     // pub is_accurate:bool
> }
> ```
> 
> Even if you just make a new Vec right before tree construction, just for purposes of querying, you should get good performance. I would try just building up a new vec right there if its not possible to reuse an existing like vec. Hope this help.


You can look at the main branch. I have optimized it by changing the usage method. The 10000 instance has been increased from 20fps to 70fps, but there is no need to destroy the use of the api. Thank you very much for your work. The collision detection performance is very good, and simple collision detection can With 80000 matrices it is also possible to achieve 60fps.Thank you for your work.

**Comment by droog126** [comment]
The improvement principle is: all instance systems run in parallel, and the collision system of Broccoli runs in a single thread at the end to obtain the read and write rights of all instances, and then distributes collision events to the instance systems.

**Comment by droog126** [comment]
After I have completed most of the basic abilities, I will invite you to experience the lawn mowing game, whirlwind killing 10,000 monsters.

**Comment by tiby312** [comment]
Awesome I would ❤️  to see it on action
